#Database
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring_web
    username: root
    password: txt1995
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  #MailSender
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 326672933882-cl7q4htvd1026pvvh41b3vbe6bbtud0f.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile

recaptcha:
  key: 6LfE15IjAAAAALrnfgMObtDj-7AlXqeLEoWCDqOV
  secret: 6LfE15IjAAAAAIZ3mcBMqUeCwx8NSzgULWFQYJm1
